// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI0yeDFnUpKKsBXDMe-zEpjfoVBgzEJCk',
    appId: '1:1000291661791:web:39aec08983d7c6acc3766a',
    messagingSenderId: '1000291661791',
    projectId: 'flutterhelloworld-ddadd',
    authDomain: 'flutterhelloworld-ddadd.firebaseapp.com',
    storageBucket: 'flutterhelloworld-ddadd.appspot.com',
    measurementId: 'G-QVC61W900E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd09o0cPwQ-2sTayy7mTosqq8I5gVLto8',
    appId: '1:1000291661791:android:47408aca89b87ad4c3766a',
    messagingSenderId: '1000291661791',
    projectId: 'flutterhelloworld-ddadd',
    storageBucket: 'flutterhelloworld-ddadd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6NPJWVN42yPx6OEwS2hNKZ7pqpty0-lI',
    appId: '1:1000291661791:ios:cf5e0c943e7b2db9c3766a',
    messagingSenderId: '1000291661791',
    projectId: 'flutterhelloworld-ddadd',
    storageBucket: 'flutterhelloworld-ddadd.appspot.com',
    iosClientId: '1000291661791-e9g5g245flamigakf0d3i84e1d8t5pkq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterHelloWorld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6NPJWVN42yPx6OEwS2hNKZ7pqpty0-lI',
    appId: '1:1000291661791:ios:cf5e0c943e7b2db9c3766a',
    messagingSenderId: '1000291661791',
    projectId: 'flutterhelloworld-ddadd',
    storageBucket: 'flutterhelloworld-ddadd.appspot.com',
    iosClientId: '1000291661791-e9g5g245flamigakf0d3i84e1d8t5pkq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterHelloWorld',
  );
}
